# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hr0Rcc_5gb_5PCGfBe7KguAbmsokZ9wB
"""

import cv2
import numpy as np
import librosa
import matplotlib.pyplot as plt

def apply_dct(image):
    # Convert the image to grayscale
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    # Apply Discrete Cosine Transform (DCT)
    dct_image = cv2.dct(np.float32(gray_image))
    return dct_image

def apply_mfcc(signal, sr):
    # Apply Mel-Frequency Cepstral Coefficients (MFCC)
    mfccs = librosa.feature.mfcc(y=signal, sr=sr, n_mfcc=13)
    return mfccs

# Load an image
image = cv2.imread('/content/00000.jpg')

# Verify if image is loaded
if image is None:
    raise ValueError("Image not loaded. Please check the path.")

# Apply DCT to the image
dct_result = apply_dct(image)

# Plot the DCT result
plt.imshow(dct_result, cmap='gray')
plt.title("DCT of Image")
plt.show()

# Load an audio file
audio_path = '/content/Test Data.wav'
signal, sr = librosa.load(audio_path)

# Verify if audio is loaded
if signal is None:
    raise ValueError("Audio not loaded. Please check the path.")

# Apply MFCC to the audio signal
mfcc_result = apply_mfcc(signal, sr)

# Plot the MFCC result
plt.figure(figsize=(10, 4))
librosa.display.specshow(mfcc_result, sr=sr, x_axis='time')
plt.colorbar()
plt.title('MFCC')
plt.tight_layout()
plt.show()

!pwd

!ls

!mkdir my_project

!cd my_project

!pwd

# Commented out IPython magic to ensure Python compatibility.
# %cd my_project

!pwd

from google.colab import files
uploaded=files.upload()

print("Helllo World ")

from google.colab import drive
drive.mount('/content/gdrive')

!pwd

!touch example2.py

# Commented out IPython magic to ensure Python compatibility.
# %cd ../../../

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gdrive/

!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd ML-Project/

!ls